### ISSUE TITLE
No module named 'build.inverse_sensor_model'

### ISSUE THREAD

**Issue by zhujinwen0924** [RobustFieldAutonomyLab/DRL_robot_exploration#1]
hello,Here is an error occured when i run 'python tf_policy_cnn',the error is 
"
Traceback (most recent call last):
  File "tf_policy_rnn.py", line 9, in <module>
    import robot_simulation as robot
  File "DRL_robot_exploration/scripts/robot_simulation.py", line 11, in <module>
    from build.inverse_sensor_model import *
ModuleNotFoundError: No module named 'build.inverse_sensor_model'

"

i found a file named "inverse_sensor_model.cpython-35m-x86_64-linux-gnu.so" in folder build,but i don't know how i can deal with it.my tensorflow version is 2.1.0,gpu is supported,and my python version is 3.6.10.

anyone can tell me why?thanks!

**Comment by zhujinwen0924** [comment]
i have handled this issue now.

**Comment by AgentEXPL** [comment]
> i have handled this issue now.

Hi, @zhujinwen0924 , I have encountered the same issue. Would like to share your solution with me? Many thanks!

**Comment by AgentEXPL** [comment]
I encounter this problem because a virtual python environment is used. The solution is to make changes in CMakeLists.txt under the DRL_robot_exploration.

**Comment by Moresweet** [comment]
Hello, I think the python interperter's location is uncorrect with your CMakeLists.txt. I use Anaconda to manage the environment in my PC. So the location should modify to my virtual envrioment interperter location.
`if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    # Force to use Python 2.7/3.5
    # set(PYTHON_EXECUTABLE /usr/local/bin/python)
    set(PYTHON_EXECUTABLE /usr/local/bin/python3)
else ()
    # set(PYTHON_EXECUTABLE /usr/bin/python)
    # set(PYTHON_EXECUTABLE /usr/bin/python3)
    # Here is your interperter's location
    set(PYTHON_EXECUTABLE /home/[username]/.conda/envs/ariadne/bin/python)
endif (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
`

**Comment by Moresweet** [comment]
Hello, I think the python interperter's location is uncorrect with your CMakeLists.txt. I use Anaconda to manage the environment in my PC. So the location should modify to my virtual envrioment interperter location.
```
if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    # Force to use Python 2.7/3.5
    # set(PYTHON_EXECUTABLE /usr/local/bin/python)
    set(PYTHON_EXECUTABLE /usr/local/bin/python3)
else ()
    # Here is your interperter location
    set(PYTHON_EXECUTABLE /home/moresweet/.conda/envs/ariadne/bin/python)
endif (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
````

**Comment by JM-Wu7** [comment]
你好，请问一下你这个tensorflow和python版本是可以跑通的吗

**Comment by JM-Wu7** [comment]
> hello,Here is an error occured when i run 'python tf_policy_cnn',the error is " Traceback (most recent call last): File "tf_policy_rnn.py", line 9, in import robot_simulation as robot File "DRL_robot_exploration/scripts/robot_simulation.py", line 11, in from build.inverse_sensor_model import * ModuleNotFoundError: No module named 'build.inverse_sensor_model'
> 
> "
> 
> i found a file named "inverse_sensor_model.cpython-35m-x86_64-linux-gnu.so" in folder build,but i don't know how i can deal with it.my tensorflow version is 2.1.0,gpu is supported,and my python version is 3.6.10.
> 
> anyone can tell me why?thanks!
你好，请问一下你这个tensorflow和python版本是可以跑通的吗

**Comment by JM-Wu7** [comment]
> hello,Here is an error occured when i run 'python tf_policy_cnn',the error is " Traceback (most recent call last): File "tf_policy_rnn.py", line 9, in import robot_simulation as robot File "DRL_robot_exploration/scripts/robot_simulation.py", line 11, in from build.inverse_sensor_model import * ModuleNotFoundError: No module named 'build.inverse_sensor_model'
> 
> "
> 
> i found a file named "inverse_sensor_model.cpython-35m-x86_64-linux-gnu.so" in folder build,but i don't know how i can deal with it.my tensorflow version is 2.1.0,gpu is supported,and my python version is 3.6.10.
> 
> anyone can tell me why?thanks!

你好，请问一下你这个tensorflow和python版本是可以跑通的吗
